spring.application.name=backend


# Ruta a tu archivo (asegúrate que la ruta sea correcta)
spring.datasource.url=jdbc:sqlite:../database/farmarosplus.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Configuración de Hibernate para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
